content/pages/team.md, content/welcoming-ansel-halliburton-to-our-board.md
@mlissner, you can replace the commented-out part with anything you want, and then move it from draft to published. Thanks!
=> Add post about Ansel joining Board

content/pages/research-papers.md
Also some formatting on previous items
=> Add recently-published papers using FLP data

posts/2021/09/28/announcing-federal-financial-disclosures.mdx
Updating with second link provided by WSJ
=> feat(fd-blog): Update WSJ link

posts/2021/09/28/announcing-federal-financial-disclosures.mdx
The main article is hidden and the visual
is more impressive as far as i can tell.
=> feat(fd-blog): Updating WSJ link

posts/2021/09/28/announcing-federal-financial-disclosures.mdx
=> feat(fd-blog): Updating WSJ link (again)

pages/index.js, posts/about.mdx, posts/mission.mdx, posts/recap.mdx, posts/recap/faq.mdx, posts/recap/privacy-policy.mdx, posts/recap/tos.mdx
Update Homepage to showcase Safari.
=> feat(Safari): Add language for the Safari release.

posts/newsletter.mdx
Mailchimp newsletter form replaced with moosend newsletter form
=> Moosend newsletter form

posts/hiring.mdx
This is just in the concept stage for now, but I will be revising it and hoping to get it launched soon. I think this humble PR could represent a huge change in the organization.
=> Rough draft for development director hiring page

posts/2021/09/28/announcing-federal-financial-disclosures.mdx, posts/donate.mdx, posts/donate/other-ways.mdx, posts/fundraiser/2021.mdx, posts/fundraiser/2021/recap.mdx, posts/fundraiser/2022.mdx, posts/fundraiser/2022/recap.mdx
=> 105 annual report

components/heroImage.js, pages/[...slug].js, pages/_app.js, posts/about.mdx, posts/fundraiser/2021.mdx, posts/fundraiser/2022.mdx, posts/pacer-facts.mdx
It's better to say we use "technology" not "software". People fear software. People hug and caress technology.
=> Mission tweaks

posts/donate.mdx
This PR updates the href attribute of the Donate buttons on  `free.law/donate/`.
=> feat(donate): Update href attribute of the Donate Now button

components/footers.js, components/headings.js, lib/mdx.js, posts/donate/help.mdx
This PR adds the FAQ page for donations for free.law
=> feat(donate): Add FAQ page for donations

lib/mdx.js, posts/donate.mdx
This PR adds a link to the Donation FAQ page on free.law/donate
=> feat(donate): Adds a link to the Donation FAQ page

posts/hiring.mdx
As discussed. 
Same as Google Doc, but tweaked the wording in the lead a little bit to make more sense.
=> Adding revised PM job posting

posts/projects/judge-db.mdx
This reverts commit ef6d38ee8a3a79495548cf1995527ba0bb1b37d5.
=> Revert "Update judge-db.mdx"

posts/2024/09/ms-edge-extension.mdx
=> feat(recap): Adds blog post announcing the extension is available for MS Edge

posts/hiring.mdx
=> feat(hiring): Add open position for AI Developer to hiring page

posts/advocacy/neutral-citations.mdx
This creates a new page that will be at free.law/advocacy/neutral-citations/
=> feat(page): New page on neutral citations

components/layout.js
=> feat(header): add Giving Tuesday banner

pages/index.js, posts/donate.mdx, posts/fundraiser/2024.mdx
Finally got this put together mostly!
=> Add the directors letter

posts/hiring.mdx
Closes #249 
Got content for empty "Open Positions" section from [this PR](https://github.com/freelawproject/free.law/pull/179/files)
=> feat(hiring): close AI position

posts/2024/12/23/bridging-the-justice-gap-ecourts.mdx
=> fix(pages): New video embed

posts/2025/03/11/semantic-search.mdx
Add a new blog post for semantic search finetuning and inception
issue: https://github.com/freelawproject/courtlistener/issues/5166
=> feat(blog): semantic search blog

posts/hiring.mdx
This is based on some notes Jenifer put together [here](https://docs.google.com/document/d/1MkEBXE1pVChtEDb6ELhihhA6ydKKrCDaXf_vcuAUkYI/edit?tab=t.0), and fixes freelawproject/internal#343.
=> Operations manager job posting (draft)

posts/2025/06/04/citator-annotation-volunteer.mdx
https://github.com/freelawproject/free.law/issues/284
=> feat(blog): volunteer opportunity for citator expert annotation project

posts/2025/06/24/calicon-2025.mdx
https://github.com/freelawproject/internal/issues/413
=> feat(blog): add calicon 2025 blog post

posts/2025/09/05/libguide.mdx, posts/donate/help.mdx, posts/hiring.mdx
This is the PR that adds the three new developer positions. 
Preview here: https://deploy-preview-320--freelaw.netlify.app/hiring
=> Add New Developer Positions

posts/2025/09/23/one-thousand-government-users.mdx
This one can get merged tonight, and we'll post about it tomorrow.
=> feat(blog): New post about govies

posts/2025/09/23/one-thousand-government-users.mdx, posts/2025/09/25/one-million-visitors.mdx
This one is set for Thursday release. 
Note that it's a branch from the first post, so it needs to merge after #341.
=> Summer series 2 one million visitors

posts/2025/09/30/justice-partners-circle.mdx
@jeniferw in a minute the preview will come through and you should be able to see the post on the blog. 
Want to take a look, proof it one last time, and hit "Merge" if you think it's ready to go?
=> New post on JPC
